
export const bagtypes = [
  "Spark Plug",
  "Air Filter",
  "Oil Filter",
  "Fuel Filter",
  "Cabin Filter",
  "Engine Oil",
  "Brake Pad",
  "Brake Disc",
  "Shock Absorber",
  "Coil Spring",
  "Wiper",
  "Battery"
];




export const storeProducts = [
  {
    id: 1,
    title: 'LED Tail Light Fit',
    img: '/images/product/lamps/1.jpg',
    price: 4650,
    artist: 'whisky',
    category:'lamps',
    subject:'Upgraded LED Tail Light Fit for BMW G30 G38',
    info: 'Fit for Customizing OEM replacement car tail light lens and housing. It’s designed to replace your existing car tail light. Fitting for your BMW G30 G38 cars. Check to be sure it fits your cars before your buying.',
    inCart: false,
    count: 0,
    total: 0,
  },
    {
    id: 2,
    title: 'Tail Light Fits',
    img: '/images/product/lamps/2.jpg',
    price: 4650,
    artist: 'whisky',
    category:'lamps',
    subject:'Customizing Through Tail Light Fits for nx200 nx300 nx200t',
    info: 'Fit for Customizing and OEM replacement car spare parts. It’s designed to replace your existing car parts. Fitting for your motorcycle upgraded types. Check to be sure it fits your LEXUS NX200 NX200T NX300 before your buying.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 3,
    title: 'LED Tail Light Fit',
    img: '/images/product/lamps/2.png',
    price: 4650,
    artist: 'whisky',
    category:'lamps',
    subject:' Modified LED Tail Light Fit for BMW X6 E71 smoked',
    info: 'Fit for Customizing and OEM replacement car spare parts. It’s designed to replace your existing car parts. Fitting for your BMW X6 E71 upgraded types. Check to be sure it fits your cars before your buying.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 4,
    title: 'LED Tail Light Fit',
    img: '/images/product/lamps/3.png',
    price: 4650,
    artist: 'whisky',
    category:'lamps',
    subject:'Custom LED Tail Light Fit for Mercedes-benz GLC 253 Smoked',
    info: 'Fit for Customizing and OEM replacement car spare parts. It’s designed to replace your existing car parts. Fitting for your Mercedes-benz GLC 253 upgraded types. Check to be sure it fits your cars before your buying.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 5,
    title: 'LED Tail Lamp Fit',
    img: '/images/product/lamps/4.png',
    price: 4650,
    artist: 'whisky',
    category:'lamps',
    subject:'Upgraded LED Tail Lamp Fit fot Mercedes-Benz GLS X167 2019-202',
    info: 'Fit for Customizing OEM replacement car tail light lens and housing. It’s designed to replace your existing car tail light. Fitting for your Mercedes-Benz GLS X167 cars. Check to be sure it fits your cars before your buying.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 6,
    title: 'LED Tail Lamp Fit',
    img: '/images/product/lamps/5.png',
    price: 4650,
    artist: 'whisky',
    category:'lamps',
    subject:'Upgraded LED Tail Lamp Fit fot AUDI A6 C7 12-15 C7PA 16-18',
    info: 'Fit for Customizing OEM replacement car tail light lens and housing. It’s designed to replace your existing car tail light. Fitting for your Audi A6 C7,C7PA cars. Check to be sure it fits your cars before your buying.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 7,
    title: 'LED Tail Light',
    img: '/images/product/lamps/6.png',
    price: 4650,
    artist: 'whisky',
    category:'lamps',
    subject:'Upgraded Automotive LED Tail Light Fit for Mercedes-Benz GLE',
    info: 'Fit for Customizing OEM replacement car tail light lens and housing. It’s designed to replace your existing car tail light. Fitting for your Mercedes-Benz GLE cars. Check to be sure it fits your cars before your buying.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
 
  
    {
    id: 9,
    title: 'LED Tail Light',
    img: '/images/product/lamps/8.png',
    price: 4650,
    artist: 'whisky',
    category:'lamps',
    subject:'Custom LED Tail Light Fit for Dodge RAM 1500',
    info: 'Fit for Customizing and OEM replacement car spare parts. It’s designed to replace your existing car parts. Fitting for your Dodge RAM 1500 upgraded types. Check to be sure it fits your RAM 1500 before your buying.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 10,
    title: 'LED Tail Lamp',
    img: '/images/product/lamps/9.png',
    price: 4650,
    artist: 'whisky',
    category:'lamps',
    subject:'Custom LED Tail Lamp Fit for Volkswagen T6',
    info: 'Fit for Customizing and OEM replacement car spare parts. It’s designed to replace your existing car parts. Fitting for your Ford Ranger upgraded types. Check to be sure it fits your Volkswagen T6 before your buying',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 11,
    title: 'LED Tail Lamp',
    img: '/images/product/lamps/10.png',
    price: 4650,
    artist: 'whisky',
    category:'lamps',
    subject:'Upgraded LED Tail Lamp Fit for Mercedes-Benz W238',
    info: 'Fit for Customizing OEM replacement car tail light lens and housing. It’s designed to replace your existing car tail light. Fitting for your Mercedes-Benz W238 cars. Check to be sure it fits your vehicle before your buying.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 12,
    title: 'LED Headlight',
    img: '/images/product/lamps/12.png',
    price: 4650,
    artist: 'whisky',
    category:'lamps',
    subject:'Modified Car LED Headlight Fit for Ford Ranger with DRL',
    info: 'Fit for Customizing and OEM replacement car spare parts. It’s designed to replace your existing car parts. Fitting for your Ford Ranger upgraded types. Check to be sure it fits your vehicle before your buying.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 13,
    title: 'LED Halogen Tail Light',
    img: '/images/product/lamps/13.png',
    price: 4650,
    artist: 'whisky',
    category:'lamps',
    subject:'Super Good LED Halogen Tail Light Fit for BMW F20',
    info: 'Fit for Customizing OEM replacement car tail light lens and housing. It’s designed to replace your existing car tail light. Fitting for your BWM F20 US cars. Check to be sure it fits your vehicle before your buying.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 14,
    title: 'Back Bumper',
    img: '/images/product/bodykits/1.jpg',
    price: 4650,
    artist: 'whisky',
    category:'bodykits',
    subject:'Refitting Vehicle Back Bumper with LED light Exhaust Tip',
    info: 'Fit for Customizing and OEM replacement car spare parts. It’s designed to replace your existing car parts. Fitting for your Honda Accord upgraded types. Check to be sure it fits your vehicle before your buying.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 15,
    title: 'front back bumper',
    img: '/images/product/bodykits/2.jpg',
    price: 4650,
    artist: 'whisky',
    category:'bodykits',
    subject:'Customizing black bodykits front back bumper fit for Toyota LX600 ',
    info: 'Fit for Customizing and OEM replacement car spare parts. It’s designed to replace your existing car parts. Fitting for your Toyota LX600 upgraded types. Check to be sure it fits your vehicle before your buying.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 16,
    title: 'Front Back Bumper',
    img: '/images/product/bodykits/3.jpg',
    price: 4650,
    artist: 'whisky',
    category:'bodykits',
    subject:'Customizing Silver Bodykits Front Back Bumper Fit for Toyota LX600 ',
    info: 'Fit for Customizing and OEM replacement car spare parts. It’s designed to replace your existing car parts. Fitting for your Toyota LX600 upgraded types. Check to be sure it fits your vehicle before your buying.',
    inCart: false,
    count: 0,
    total: 0,
  },
  

      {
    id: 18,
    title: 'Front Bumper',
    img: '/images/product/bodykits/5.jpg',
    price: 4650,
    artist: 'whisky',
    category:'bodykits',
    subject:'Upgraded Bodykits Front Bumper Replacement Fit for Volkswagen Scirocco',
    info: 'Fit for Customizing and OEM replacement car spare parts. It’s designed to replace your existing car parts. Fitting for your upgraded Volkswagen Scirocco types. Check to be sure it fits your vehicle before your buying.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 19,
    title: 'Headligh',
    img: '/images/product/bodykits/6.jpg',
    price: 4650,
    artist: 'whisky',
    category:'bodykits',
    subject:'Upgraded Customizing car Bodykits Car Headlight Car Taillight 10-14 to 15-up Volkswagen Scirocco R',
    info: 'Fit for Customizing and OEM replacement car spare parts. It’s designed to replace your existing car parts. Fitting for your Volkswagen Scirocco R 2015-UP upgraded types. Check to be sure it fits your vehicle before your buying.',
    inCart: false,
    count: 0,
    total: 0,
  }


]
